CONFIG_ZMK_BLE_EXPERIMENTAL_FEATURES=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

CONFIG_ZMK_SLEEP=n
CONFIG_ZMK_EXT_POWER=y

CONFIG_ZMK_STUDIO=n

# ---------- Display ----------
CONFIG_SPI=y
CONFIG_MIPI_DBI=y


# ZMK display subsystem
CONFIG_ZMK_DISPLAY=y
CONFIG_SSD1306=n
CONFIG_ZMK_DISPLAY_BLANK_ON_IDLE=y

CONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILT_IN=n
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y
CONFIG_MLEGO_BONGO_CAT=n

CONFIG_DISP_WIDTH=200
CONFIG_DISP_HEIGHT=200
CONFIG_DISP_CANVAS=64
CONFIG_DISP_ROTATE=1800

# ePaper is 1-bit (black/white) monochrome
CONFIG_LV_COLOR_DEPTH_1=y

# ---------- Logging (USB CDC) ----------
CONFIG_ZMK_USB_LOGGING=y
CONFIG_LOG=y
CONFIG_DISPLAY_LOG_LEVEL_DBG=y
CONFIG_SPI_LOG_LEVEL_DBG=y
CONFIG_MIPI_DBI_LOG_LEVEL_DBG=y

CONFIG_LOG_BUFFER_SIZE=8192
CONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS=8000
